# Generated by Django 5.1.2 on 2025-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("doctor", "Главный врач"),
                    ("storekeeper", "Заведующий складом"),
                    ("admin", "Админ сайта"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
