# Generated by Django 5.1.2 on 2025-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("doctor", "Главный врач"),
                    ("storekeeper", "Заведующий складом"),
                    ("zavOtdel", "Заведубщий отделением"),
                    ("Registrat", "Работник регистратуры"),
                    ("labor", "лаборант"),
                    ("zavDiagn", "Зав.лаб по диагностике"),
                    ("ZavIzgot", "Зав.лаб по изготовлению"),
                    ("FARMAC", "Фармацефт"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
